### ISSUE TITLE
get errors while running setup.sh

### ISSUE THREAD

**Issue by Ghostish** [ArteMisc/libstodium#1]
I am using Ubuntu 14.04 LTS  ,  but I always get errors when running the setup.sh , in terminal it shows:
cp: 无法获取"/usr/local/lib/libsodium._" 的文件状态(stat): 没有那个文件或目录, in English it means "cp: could not find  the files stat of "/usr/local/lib/libsodium._" : no such file or directory" ..  
I don't really know what the error means but I found that it might be caused by the "complie.sh" file  in kalium -jni

**Comment by ArteMisc** [comment]
It looks like the command that causes the error is this one: https://github.com/ArteMisc/libstodium/blob/master/jni/compile.sh#L34

If that is the case, then it might be one of two reasons I can think of right now:
1) The command requires super-user rights, is your user allowed to use sudo?
2) libsodium.\* files don't exist, which means there could be a problem during the installation of libsodium. Do you get any other warnings during the installation?

If you could confirm whether either of these is the case, that would be very helpful. I'll try to re-run the setup with a clean system as well to see if I can reproduce the error.

**Comment by Ghostish** [comment]
My problem should be the second you listed above . There is no any libsodium.\* files in  /usr/local/lib/

**Comment by ArteMisc** [comment]
The script did not include commands to install libsodium on the host machine, this should now be fixed. I didn't notice because I installed libsodium separately before starting this project. Thanks for bringing this to my attention, let me know if it works!
