### ISSUE TITLE
Errors in installing  libsodium

### ISSUE THREAD

**Issue by Ghostish** [ArteMisc/libstodium#2]
I ran the latest script and I got errors while intalling libsodium . In terminal its showed : 
fatal: reference is not a tree: beee6aa38c3c7c5a65aa1004b68be8a0aa74fdda
Unable to checkout 'beee6aa38c3c7c5a65aa1004b68be8a0aa74fdda' in submodule path 'libsodium'

**Comment by ArteMisc** [comment]
The libsodium submodule was a reference to a private fork of the libsodium master branch that only I could access. I switched it to the stable branch of the original repo, it should work now.

Let me know if there's any more errors!

**Comment by Ghostish** [comment]
Thanks . The setup script works well this time . But I don't really know how to use it in my project.Need I copy the whole 'libstodium' directory to my project root or just the .so files and java files ?

**Comment by ArteMisc** [comment]
The project is setup as a Gradle module for Android Studio, so you should be able to import it as such.

To import the project you can go to your project's Module Settings -> Add Module -> Import Gradle Project, then browse to /path/to/libstodium (this can be a subdirectory of your project). After that you should be able to simply add the line `compile project(':libstodium')` in the `dependencies {}` block of the Gradle build file of every module within the project that requires libstodium.

In the future there might be support for building a .jar file that can be imported or maybe a Maven project, but for now simply importing the module in your project should do the trick.

**Comment by Ghostish** [comment]
Thanks : )
